version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5-0
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
      - --features=dpop
    environment:
      - KC_HTTP_ENABLED=true
      - KC_HTTP_RELATIVE_PATH=/idp
      - KC_HTTP_PORT=8446
      - KC_HTTPS_PORT=8445
      - KC_HTTPS_CERTIFICATE_FILE=/etc/ssl/certs/keycloak.tls.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/ssl/certs/keycloak.tls.key
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=password
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak_password
    volumes:
      - ../services/authentic-source/keycloak/realms/:/opt/keycloak/data/import
      - ../services/authentic-source/keycloak/certs/keycloak.tls.crt:/etc/ssl/certs/keycloak.tls.crt
      - ../services/authentic-source/keycloak/certs/keycloak.tls.key:/etc/ssl/certs/keycloak.tls.key
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_password
    volumes:
      - docker-compose_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    # command: redis-server --requirepass mypassword
    volumes:
      - redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      interval: 1s
      timeout: 3s
      retries: 30

  crl_publisher:
    image: navzar05/crl-publisher:dev 
    container_name: crl_publisher
    environment:
      - TOKEN_PIN=Andrei2002#
      - CERT_LABEL=IssuerECKey
      - PKCS11_LIB_PATH=/usr/lib/libeToken.so
      - REDIS_HOST=redis
      - REDIS_PASSWORD=mypassword
      - INITIAL_PUBLISH=1
      - ABI_FILE_PATH=./abi.json
      - PRIVATE_KEY=0x3d0be1f04e66966e5c2138f70b50faffc5634a36b50ef8d76d80093dc9c2f650
      - CONTRACT_ADDRESS=0xCf2D2500092761583af3EB64a020584c3A424D1E
      - RPC_URL=https://ethereum-holesky-rpc.publicnode.com
      - IPFS_PINNING_ENDPOINT=https://api.pinata.cloud/pinning/pinFileToIPFS
      - PINATA_API_KEY=a2e74131d851ebe3156a
      - PINATA_SECRET_KEY=264d2b858cd60a2c9ff1b8ea4e6a73ef4ab1410c4fb4d612e7f81ea6a22f35ec
      - REDIS_PORT=6379
      - INITIAL_PUBLISH=1
    volumes:
      - /run/pcscd/pcscd.comm:/run/pcscd/pcscd.comm
    # depends_on:
    #   redis:
    #     condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "443:443"
    volumes:
      - ../services/nginx-proxy/certs/nginx.crt:/etc/nginx/nginx.crt:ro
      - ../services/nginx-proxy/certs/nginx.key:/etc/nginx/nginx.key:ro
      - ../services/nginx-proxy/nginx_dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak

volumes:
  docker-compose_postgres_data:
    external: true
  redis_data: