version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5-0
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
      - --features=dpop
    environment:
      - KC_HOSTNAME=issuer.myddns.me
      - KC_HOSTNAME_URL=https://issuer.myddns.me/idp
      - KC_HOSTNAME_ADMIN_URL=https://issuer.myddns.me/idp
      - KC_HTTP_RELATIVE_PATH=/idp
      - KC_HTTPS_PORT=8445
      - KC_HTTPS_CERTIFICATE_FILE=/etc/ssl/certs/keycloak.tls.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/ssl/certs/keycloak.tls.key
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      # pentru postgres
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak_password
    volumes:
      - ../services/authentic-source/keycloak/extra/health-check.sh:/opt/keycloak/health-check.sh
      - ../services/authentic-source/keycloak/realms/:/opt/keycloak/data/import
      - ../services/authentic-source/keycloak/certs/keycloak.tls.crt:/etc/ssl/certs/keycloak.tls.crt
      - ../services/authentic-source/keycloak/certs/keycloak.tls.key:/etc/ssl/certs/keycloak.tls.key
      - ../services/authentic-source/keycloak/themes:/opt/keycloak/themes
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_password
    volumes:
      - docker-compose_postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "443:443"
    volumes:
      - ../services/nginx-proxy/certs/fullchain.pem:/etc/nginx/nginx.crt:ro
      - ../services/nginx-proxy/certs/privkey.pem:/etc/nginx/nginx.key:ro
      - ../services/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - issuer-server


  issuer-server:
    image: issuer_server:experimental
    container_name: issuer_server
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /run/pcscd/pcscd.comm:/run/pcscd/pcscd.comm
    environment:
      - PKCS11_MODULE=/usr/lib/libeToken.so
    depends_on:
      - keycloak

# volumes:
#   postgres_data:
volumes:
  docker-compose_postgres_data:
    # external: true
